Update enter script to accomodate for other shells

diff --git a/dep/enter b/dep/enter
--- a/dep/enter
+++ b/dep/enter
@@ -6,26 +6,21 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-SHELL="/bin/bash";
+FALLBACK="bash"
+SHELL="bash";
+PREPEND=
 
 # check if current user is not in group docker
 if ! groups $USER | grep &>/dev/null '\bdocker\b'; then
-    # check if current user is not root
-    if [ "$EUID" -ne 0 ]; then
-        #if sudo docker exec -it "docker_$@_1" which zsh >&/dev/null && sudo docker exec -it "docker_$@_1" test -d "/home/web/.oh-my-zsh"; 
-        #    then SHELL="$(sudo docker exec -it "docker_$@_1" which zsh)";
-        #fi
-        sudo docker exec -it "docker_$@_1" ${SHELL//$'\r'/}
-    else
-        #if docker exec -it "docker_$@_1" which zsh >&/dev/null && docker exec -it "docker_$@_1" test -d "/home/web/.oh-my-zsh";
-        #    then SHELL="$(docker exec -it "docker_$@_1" which zsh)";
-        #fi
-        docker exec -it "docker_$@_1" ${SHELL//$'\r'/}
-    fi
-else
-    #if docker exec -it "docker_$@_1" which zsh >&/dev/null && docker exec -it "docker_$@_1" test -d "/home/web/.oh-my-zsh";
-    #    then SHELL="$(docker exec -it "docker_$@_1" which zsh)";
-    #fi
-    docker exec -it "docker_$@_1" ${SHELL//$'\r'/}
+    PREPEND="sudo"
 fi
 
+cd $(devctl dockerdir)
+${PREPEND} docker-compose exec $@ which $SHELL > /dev/null 2>&1
+EXITCODE=$?
+# check if latest command exit code is not 0
+if [ ! $EXITCODE = "0" ]; then
+    ${PREPEND} docker-compose exec $@ $FALLBACK
+else
+    ${PREPEND} docker-compose exec $@ $SHELL
+fi
